### ISSUE TITLE
[QUESTION] New version publication

### ISSUE THREAD

**Issue by Greybird** [EasyPost/easyvcr-csharp#61]
Hello,

Sorry to raise an issue for this matter, but discussions are not available on this repository.

I'd like to take advantage of recent fixes to remove reflection I had to integrate when using the library in version 0.9.0.
Would you have plans to release a new version of the library in the near future?

Thanks for your feedback on the matter!

**Comment by nwithan8** [comment]
Hello!

Yes, we are in the process of getting a release ready to go for this. We are having to finish up some internal housekeeping before we can cut a new release.
